### ISSUE TITLE
compilation failure

### ISSUE THREAD

**Issue by Dowwie** [sfackler/rust-postgres-range#8]
when I use postgres = "0.15.1"   and postgres_range = "0.8.2"   ,  cargo fails to compile

This is the compilation error:

error[E0308]: mismatched types                           
   --> /.../.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.11.4/src/error/sqlstate.rs:485:12
    |                                                                    
485 |       disps: &[                                                
    |  ____________^                          
486 | |         (0, 10),
487 | |         (1, 206),                                                    
488 | |         (0, 38),                            
...   |                                        
533 | |         (0, 105),                                   
534 | |     ],                                                    
    | |_____^ expected enum `phf::Slice`, found reference
    |
    = note: expected type `phf::Slice<(u32, u32)>`
               found type `&[({integer}, {integer}); 48]`
help: try using a variant of the expected type
    |                               
485 |     disps: phf::Slice::Static(&[(0, 10), (1, 206), (0, 38), (0, 10), (0, 0), (1, 2), (0, 43), (0, 0),
486 |   (2, 4), (0, 153), (0, 34), (0, 8), (0, 29), (0, 42), (0, 52), (0, 0),
487 |   (1, 51), (2, 198), (9, 158), (1, 18), (0, 19), (0, 65), (1, 118), (1, 125),                                                                          
488 |   (3, 235), (0, 87), (0, 21), (3, 164), (0, 3), (4, 117), (11, 120), (0, 115),
489 |   (40, 222), (0, 8), (8, 124), (1, 142), (0, 0), (0, 0), (10, 78), (1, 173),
490 |   (10, 37), (2, 209), (18, 30), (1, 19), (0, 10), (0, 233), (2, 149),
  ...

error[E0308]: mismatched types
   --> /.../.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.11.4/src/error/sqlstate.rs:535:14
    |
535 |       entries: &[
    |  ______________^
536 | |         ("42P03", SqlState::DuplicateCursor),
537 | |         ("22019", SqlState::InvalidEscapeCharacter),
538 | |         ("22022", SqlState::IndicatorOverflow),
...   |
771 | |         ("02000", SqlState::NoData),
772 | |     ]
    | |_____^ expected enum `phf::Slice`, found reference
    |
    = note: expected type `phf::Slice<(&str, error::sqlstate::SqlState)>`
               found type `&[(&str, error::sqlstate::SqlState); 236]`
help: try using a variant of the expected type
    |
535 |     entries: phf::Slice::Static(&[("42P03", SqlState::DuplicateCursor),
536 |   ("22019", SqlState::InvalidEscapeCharacter),
537 |   ("22022", SqlState::IndicatorOverflow),
538 |   ("25002", SqlState::BranchTransactionAlreadyActive),
539 |   ("2F004", SqlState::SqlRoutineReadingSqlDataNotPermitted),
540 |   ("23505", SqlState::UniqueViolation),
  ...

error: aborting due to 2 previous errors
error: Could not compile `postgres`.

**Comment by sfackler** [comment]
The published version of postgres-range uses an out of date version of postgres.

**Comment by Dowwie** [comment]
Thanks for the quick response.  It works from a cloned repo.
